apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"fluentbit.fluent.io/v1alpha2","kind":"ClusterFilter","metadata":{"annotations":{"meta.helm.sh/release-name":"fluent-operator","meta.helm.sh/release-namespace":"fluent"},"creationTimestamp":"2025-09-15T18:46:05Z","generation":1,"labels":{"app.kubernetes.io/managed-by":"Helm","fluentbit.fluent.io/component":"logging","fluentbit.fluent.io/enabled":"true"},"managedFields":[{"apiVersion":"fluentbit.fluent.io/v1alpha2","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:meta.helm.sh/release-name":{},"f:meta.helm.sh/release-namespace":{}},"f:labels":{".":{},"f:app.kubernetes.io/managed-by":{},"f:fluentbit.fluent.io/component":{},"f:fluentbit.fluent.io/enabled":{}}},"f:spec":{".":{},"f:filters":{},"f:match":{}}},"manager":"helm","operation":"Update","time":"2025-09-15T18:46:05Z"}],"name":"kubernetes","resourceVersion":"399640","uid":"163ba11b-b288-4bfd-8ebe-2e5e16f7dce4"},"spec":{"filters":[{"kubernetes":{"annotations":true,"kubeCAFile":"/var/run/secrets/kubernetes.io/serviceaccount/ca.crt","kubeTokenFile":"/var/run/secrets/kubernetes.io/serviceaccount/token","kubeURL":"https://kubernetes.default.svc:443","labels":true}},{"nest":{"addPrefix":"kubernetes_","nestedUnder":"kubernetes","operation":"lift"}},{"modify":{"rules":[{"remove":"stream"},{"remove":"kubernetes_pod_id"},{"remove":"kubernetes_host"},{"remove":"kubernetes_container_hash"},{"remove":"kubernetes_annotations_checksum_config"},{"remove":"kubernetes_docker_id"}]}},{"nest":{"nestUnder":"k8s","operation":"nest","removePrefix":"kubernetes_","wildcard":["kubernetes_*"]}}],"match":"kube.*"}}
    meta.helm.sh/release-name: fluent-operator
    meta.helm.sh/release-namespace: fluent
  creationTimestamp: "2025-09-15T18:46:05Z"
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
    fluentbit.fluent.io/component: logging
    fluentbit.fluent.io/enabled: "true"
  name: kubernetes
  resourceVersion: "411761"
  uid: 163ba11b-b288-4bfd-8ebe-2e5e16f7dce4
spec:
  filters:
  - kubernetes:
      annotations: true
      kubeCAFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      kubeTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubeURL: https://kubernetes.default.svc:443
      labels: true
  - nest:
      addPrefix: kubernetes_
      nestedUnder: kubernetes
      operation: lift
  - modify:
      rules:
      - remove: stream
      - remove: kubernetes_pod_id
      - remove: kubernetes_host
      - remove: kubernetes_container_hash
      - remove: kubernetes_annotations_checksum_config
      - remove: kubernetes_docker_id
  - nest:
      nestUnder: k8s
      operation: nest
      removePrefix: kubernetes_
      wildcard:
      - kubernetes_*
  match: kube.*



  "spec": {
    "filters": [
      {
        "kubernetes": {
          "annotations": true,
          "kubeCAFile": "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt",
          "kubeTokenFile": "/var/run/secrets/kubernetes.io/serviceaccount/token",
          "kubeURL": "https://kubernetes.default.svc:443",
          "labels": true
        }
      },
      {
        "nest": {
          "addPrefix": "kubernetes_",
          "nestedUnder": "kubernetes",
          "operation": "lift"
        }
      },
      {
        "modify": {
          "rules": [
            {
              "remove": "stream"
            },
            {
              "remove": "kubernetes_pod_id"
            },
            {
              "remove": "kubernetes_host"
            },
            {
              "remove": "kubernetes_container_hash"
            },
            {
              "remove": "kubernetes_annotations_checksum_config"
            },
            {
              "remove": "kubernetes_docker_id"
            }
          ]
        }
      },
      {
        "nest": {
          "nestUnder": "k8s",
          "operation": "nest",
          "removePrefix": "kubernetes_",
          "wildcard": [
            "kubernetes_*"
          ]
        }
      }
    ],
    "match": "kube.*"
